--- #YAML:1.0
name:               Net-RabbitMQ-Java
version:            2.030101
abstract:           Perl bindings for the RabbitMQ Java AMQP client library
author:
    - Alessandro Ranellucci <aar@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  6.31
build_requires:
    Data::UUID:      0
    File::ShareDir:  0
    Inline::Java:    0.53
    Test::More:      0.96
requires:  {}
resources:
    repository:  git://git@github.com:alexrj/Net-RabbitMQ-Java.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
